# Generated by Django 6.0.5 on 2026-08-22 10:49

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('my_task', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Вставте зображення для завдання.', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, help_text='Опишіть завдання.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_termin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
