# Generated by Django 6.0.5 on 2026-09-05 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_termin',
            field=models.DateField(blank=True, help_text='Вкажіть термін виконання завдання. (DD/MM/YYYY)', null=True),
        ),
    ]
