# Generated by Django 6.0.5 on 2026-09-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0004_task_created_at_alter_task_progress_termin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_termin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
