# Generated by Django 6.0.5 on 2026-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_task', '0005_alter_task_description_alter_task_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Потрібно зробити'), ('in_progress', 'У процесі'), ('done', 'Готово')], default='todo', max_length=20),
        ),
    ]
